export enum UserAuthScope {
  PROFILE = 'PROFILE',
  CREATE_USER = 'CREATE_USER',
  EDIT_USER = 'EDIT_USER',
  CREATE_SYSTEM = 'CREATE_SYSTEM',
  EDIT_SYSTEM = 'EDIT_SYSTEM',
  CREATE_VERSION = 'CREATE_VERSION',
}
